analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.chopper.dart"
    - "**/*.config.dart"
    - "**/*.gr.dart"
    - "android/*"
    - "ios/*"
    - ".fvm/*"
    - "web/*"
    - "build/"
    - "assets/"
    - ".vscode/"
    - ".idea/"
    - ".dart_tool/"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: true
  errors:
    missing_required_param: error
    missing_return: error
    public_member_api_docs: ignore
    lines_longer_than_80_chars: ignore
    cascade_invocations: ignore
    prefer_if_elements_to_conditional_expressions: ignore
    avoid_redundant_argument_values: ignore
    require_trailing_commas: ignore
    invalid_annotation_target: ignore
    sort_pub_dependencies: ignore
    prefer_asserts_with_message: ignore
    use_build_context_synchronously: ignore
    avoid_dynamic_calls: ignore
    omit_local_variable_types: ignore

linter:
  rules:
    avoid_catching_errors: false
    unawaited_futures: false
    library_private_types_in_public_api: false
