name: swivt_challenge
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.14.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  dio: ^4.0.6
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
  freezed_annotation: ^1.0.0
  hive: ^2.1.0
  path_provider: ^2.0.9
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0
  equatable: ^2.0.3
  shimmer: ^2.0.0
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  integration_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  freezed: ^1.0.0
  json_serializable: ^6.1.6
  very_good_analysis: ^2.1.2

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
  fonts:
    - family: SF
      fonts:
        - asset: assets/font/SF.ttf
